name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Detekt
        run: ./gradlew detekt
      - name: Test
        run: ./gradlew test
      - name: Build
        run: ./gradlew build