name: Release

on:
  release:
    types: [released]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Build
        run: ./gradlew build
      - name: Get jar path
        run: echo $(ls depstoml/build/libs/depstoml-*.jar)
      - name: Attach jar to latest release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LATEST_RELEASE_TAG: ${{github.ref_name}}
        run: gh release upload $LATEST_RELEASE_TAG $(ls depstoml/build/libs/depstoml-*.jar)